package com.techelevator.dao;

import com.techelevator.model.ProductionRun;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.rowset.SqlRowSet;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Component
public class JdbcProductionRunDao implements ProductionRunDao {
    private final String TABLE = "production_run";
    private final JdbcTemplate jdbcTemplate;

    public JdbcProductionRunDao(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * @return All recorded production runs.
     */
    @Override
    public List<ProductionRun> readAll() {
        List<ProductionRun> productionRuns = new ArrayList<>();
        String sql = "select * from " + TABLE;

        SqlRowSet results = jdbcTemplate.queryForRowSet(sql);
        while (results.next()) {
            ProductionRun productionRun = mapRowToModel(results);
            productionRuns.add(productionRun);
        }

        return productionRuns;
    }

    /**
     * @param productionRunId Serialized id generated by the database
     * @return The production run with the given id.
     */
    @Override
    public ProductionRun read(int productionRunId) {
        String sql = "select * from " + TABLE + " where id = ?";
        SqlRowSet results = jdbcTemplate.queryForRowSet(sql, productionRunId);
        if (results.next())
            return mapRowToModel(results);
        else return null;
    }

    /**
     * @param productCode The product id
     * @return All production runs for the given product code.
     */
    @Override
    public List<ProductionRun> readForProduct(int productCode) {
        List<ProductionRun> productionRuns = new ArrayList<>();
        String sql = "select * from " + TABLE + " where product_code = ?";
        SqlRowSet results = jdbcTemplate.queryForRowSet(sql, productCode);
        while (results.next())
            productionRuns.add(mapRowToModel(results));

        return productionRuns;
    }

    /**
     * @param id The production run id
     * @return true if the production run exists, false otherwise
     */
    @Override
    public boolean exists(int id) {
        String sql = "SELECT count(*) FROM "+TABLE+" WHERE id = ?";
        int count = jdbcTemplate.queryForObject(sql, new Object[] {id}, Integer.class);
        return count > 0;
    }

    /**
     * @param id The product id
     * @return true if production runs exist for the product, false otherwise
     */
    @Override
    public boolean existsForProduct(int id) {
        String sql = "SELECT count(*) FROM "+TABLE+" WHERE product_code = ?";
        boolean exists = false;
        int count = jdbcTemplate.queryForObject(sql, new Object[] {id}, Integer.class);
        exists = count > 0;
        return exists;
    }

    @Override
    public boolean create(ProductionRun run) {
        String sql = "insert into " + TABLE + " (product_code, production_date, quantity, status, notes) values (?,?,?,?,?)";
        return jdbcTemplate.update(sql, run.getProductCode(), run.getProductionDate(), run.getQuantity(), run.getStatus(), run.getNotes()) == 1;
    }

    ProductionRun mapRowToModel(SqlRowSet results) {
        ProductionRun productionRun = new ProductionRun();
        productionRun.setId(results.getInt("id"));
        productionRun.setProductCode(results.getInt("product_code"));
        productionRun.setProductionDate(results.getDate("production_date"));
        productionRun.setQuantity(results.getInt("quantity"));
        productionRun.setStatus(results.getString("status"));
        productionRun.setNotes(results.getString("notes"));
        return productionRun;
    }
}
