package com.techelevator.controller;

import com.techelevator.dao.ProductDao;
import com.techelevator.model.Product;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/scooby-cards")
@CrossOrigin
public class ProductController {
    private final ProductDao productDao;

    public ProductController(ProductDao productDao) {
        this.productDao = productDao;
    }

    /**
     * Returns all products.
     * @return
     */
    @RequestMapping(value = "", method = RequestMethod.GET)
    public List<Product> getAll() {
        return productDao.getAllProducts();
    }

    /**
     * Return product for a given ID.
     * @param id
     * @return
     */
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public Product getWithId(@PathVariable int id) {
        return productDao.getProductById(id);
    }

    /**
     * Adds a new product to the database.  The product's id will be automatically generated by the database.
     * @param product The desired product values.
     * @return The completed product with auto-generated ID.
     */
    @RequestMapping(method = RequestMethod.POST)
    public Product post(@RequestBody Product product) {
        return productDao.createProduct(product);
    }

}
